project:
  type: website
  output-dir: docs

website:
  title: "My Life"
  navbar:
    logo: imgs/skull.jpg
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: vapor
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



